import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "primary-fixed-dim": "#adc6ff",
        "on-secondary": "#3c0091",
        "surface-container-low": "#1a1b22",
        "surface": "#12131a",
        "surface-variant": "#33343c",
        "on-tertiary-fixed": "#311400",
        "surface-container-highest": "#33343c",
        "on-primary-container": "#00285d",
        "on-error": "#690005",
        "secondary": "#d0bcff",
        "on-secondary-fixed": "#23005c",
        "on-tertiary-container": "#461f00",
        "secondary-container": "#571bc1",
        "outline-variant": "#424754",
        "primary-fixed": "#d8e2ff",
        "surface-container-lowest": "#0d0e15",
        "on-secondary-fixed-variant": "#5516be",
        "on-primary-fixed-variant": "#004395",
        "error": "#ffb4ab",
        "surface-tint": "#adc6ff",
        "primary": "#adc6ff",
        "tertiary-fixed": "#ffdcc6",
        "inverse-on-surface": "#2f3038",
        "on-tertiary": "#502400",
        "secondary-fixed": "#e9ddff",
        "outline": "#8c909f",
        "inverse-primary": "#005ac2",
        "tertiary": "#ffb786",
        "on-secondary-container": "#c4abff",
        "on-surface-variant": "#c2c6d6",
        "inverse-surface": "#e3e1ec",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#723600",
        "surface-bright": "#383941",
        "secondary-fixed-dim": "#d0bcff",
        "on-background": "#e3e1ec",
        "surface-dim": "#12131a",
        "primary-container": "#4d8eff",
        "on-primary-fixed": "#001a42",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#292931",
        "on-surface": "#e3e1ec",
        "on-primary": "#002e6a",
        "tertiary-fixed-dim": "#ffb786",
        "surface-container": "#1e1f26",
        "tertiary-container": "#df7412"
      },
      spacing: {
        "section_gap": "32px",
        "sidebar_width": "240px",
        "component_gap": "16px",
        "inline_gap": "8px",
        "grid_gutter": "16px",
        "header_height": "56px",
        "page_padding": "24px"
      },
      fontFamily: {
        "body-sm": ["var(--font-inter)"],
        "data-tabular": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "h2": ["var(--font-geist)"],
        "label-mono": ["var(--font-jetbrains-mono)"],
        "body-lg": ["var(--font-inter)"],
        "display": ["var(--font-geist)"],
        "h1": ["var(--font-geist)"]
      },
      fontSize: {
        "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
        "data-tabular": ["13px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "h2": ["18px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-mono": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "h1": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
